TehranMap/urls.py
from django.urls import include, path
from . import views
from django.conf.urls import url
app_name='tehranMap'
urlpatterns = [
    path('compelexes/', views.map , name='map'),
    path('compelexes/<int:region_id>', views.CompelexMenu , name='menu'),
    path('compelexes/<int:region_id>/<int:group_id>', views.list , name='list'),
    # url(r'^register/$', views.signup, name='register'),

]

Wellness/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib.auth import views
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    # url(r'^login/$', views.LoginView.as_view(), name='login'),
    # url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    path('',include('TehranMap.urls')),
    path('accounts/', include('accounts.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path,include
from . import views

# app_name='accounts'

urlpatterns = [
    path('' , include('django.contrib.auth.urls')),
    # path('profile/' , views.profile , name = 'profile'),
    path('register/' , views.register , name = 'register'),
]

# accounts/login/ [name='login']
# accounts/register/ [name='register']
# accounts/logout/ [name='logout']
# accounts/password_change/ [name='password_change']
# accounts/password_change/done/ [name='password_change_done']
# accounts/password_reset/ [name='password_reset']
# accounts/password_reset/done/ [name='password_reset_done']
# accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
# accounts/reset/done/ [name='password_reset_complete']

TehranMap/models.py
from django.db import models

# Create your models here.

class Group(models.Model):
    name=models.CharField(max_length=50)
    def __str__(self):
        return self.name

class Club(models.Model):
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=300)
    phone = models.CharField(max_length=8)
    region = models.CharField(max_length=2 , null=True)
    group = models.ForeignKey(Group , on_delete=models.SET_NULL , null=True , blank=True)
    def __str__(self):
        return self.name

accounts/models.py
from django.db import models

# Create your models here.

TehranMap/views.py
from django.shortcuts import render , redirect
from django.http import HttpResponse

from django.views.generic import TemplateView

from .models import Club
from .models import Group

from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
# Create your views here.

# def index(request):
#     return render(request, 'index.html')

@login_required
def list(request ,region_id , group_id):
    club = Club.objects.filter(region=region_id).filter(group_id=group_id)
    # club_group = Group.objects.get(group_id=club.name)
    return render(request, 'list.html', {'clubs':club})


def map(request):
    club = Club.objects.all()
    return render(request, 'map/map.html', {'club':club})


# def signup(request):
#     if request.user.is_authenticated:
#         return redirect('/')
#     if request.method == 'POST':
#         form = UserCreationForm(request.POST)
#         if form.is_valid():
#             form.save()
#             username = form.cleaned_data.get('username')
#             raw_password = form.cleaned_data.get('password1')
#             user = authenticate(username=username, password=raw_password)
#             login(request, user)
#             return redirect('/')
#     else:
#
#         form = UserCreationForm()
#
#         return render(request, 'registration/signup.html', {'form': form})


#
# class CompelexMenu(TemplateView):
#
#     template_name='menu.html'
#
#
# def get_context_data(self, **kwargs):
#     # Call the base implementation first to get a context
#     context = super().get_context_data(**kwargs)
#     # Add in a QuerySet of all the books
#     context['clubs'] = Club.objects.get(region=region_id)
#     return context

def CompelexMenu(request, region_id ):
    # clubs= Club.objects.filter(region=region_id)

    return render(request , 'menu.html' , {'region': region_id })

Wellness/views.py
from django.shortcuts import render , redirect
from django.http import HttpResponse




from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):

    return render(request, 'index.html')

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
# Create your views here.
# def profile(request):
#     return render(request , 'accounts/profile.html')

def register(request):
    if request.method == 'POST':

        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()

            return redirect('/')
    else:
        form = UserCreationForm()

    return render(request, 'registration/signup.html', {'form' : form})


TehranMap/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>


    <!-- Favicons -->
  <link rel="shortcut icon" type="image/png" href={% static 'photo/favicon.png' %} />

  <!-- Bootstrap CSS File -->
  <link href={% static 'mylib/bootstrap/css/bootstrap.min.css' %} rel="stylesheet">

  <!-- mylibraries CSS Files -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
  <link href={% static 'mylib/font-awesome/css/font-awesome.min.css' %} rel="stylesheet">
  <link href={% static 'mylib/animate/animate.min.css' %} rel="stylesheet">
  <link href={% static 'mylib/ionicons/css/ionicons.min.css' %} rel="stylesheet">
  <link href={% static 'mylib/owlcarousel/assets/owl.carousel.min.css' %} rel="stylesheet">
  <link href={% static 'mylib/lightbox/css/lightbox.min.css' %} rel="stylesheet">

  <!-- Main Stylesheet File -->
  <link href={% static 'css/base.css' %} rel="stylesheet">

    <!---------------------------------------------->
    <style type="text/css">
    @font-face {
      font-family: vazir-thin;
      src: url({% static "font/vazir-font-v19.1.0/Farsi-Digits/Vazir-Thin-FD.woff" %});
    }
    @font-face {
      font-family: vazir-medium;
      src: url({% static "font/vazir-font-v19.1.0/Farsi-Digits/Vazir-Medium-FD.woff" %});
    }
    @font-face {
      font-family: vazir-bold;
      src: url({% static "font/vazir-font-v19.1.0/Farsi-Digits/Vazir-Bold-FD.woff" %});
    }
    @font-face {
      font-family: Vazir Code;
      src: url('{% static "font/vazir-code-font-v1.1.1/Vazir-Code.eot" %}');
      src: url('{% static "font/vazir-code-font-v1.1.1/Vazir-Code.eot" %}'),
           url('{% static "font/vazir-code-font-v1.1.1/Vazir-Code.woff" %}') format('woff'),
           url('{% static "font/vazir-code-font-v1.1.1/Vazir-Code.ttf" %}') format('truetype');
      font-weight: normal;
    }

    @font-face {
      font-family: Vazir Code Hack;
      src: url('{% static "font/vazir-code-font-v1.1.1/Vazir-Code-Hack.eot" %}');
      src: url('{% static "font/vazir-code-font-v1.1.1/Vazir-Code-Hack.eot" %}'),
           url('{% static "font/vazir-code-font-v1.1.1/Vazir-Code-Hack.woff" %}') format('woff'),
           url('{% static "font/vazir-code-font-v1.1.1/Vazir-Code-Hack.ttf" %}') format('truetype');
      font-weight: normal;
    }
  </style>
</head>
<body id="page-top">
{#    <nav class="navbar navbar-b navbar-trans navbar-expand-md fixed-top" id="mainNav">#}
{#        <div class="container">#}
{#          <a class="navbar-brand js-scroll" href="#page-top">Wellnes</a>#}
{#          <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarDefault"#}
{#            aria-controls="navbarDefault" aria-expanded="false" aria-label="Toggle navigation">#}
{#            <span></span>#}
{#            <span></span>#}
{#            <span></span>#}
{#          </button>#}
{#          <div class="navbar-collapse collapse justify-content-end" id="navbarDefault">#}
{#            <ul class="navbar-nav">#}
{#              <li class="nav-item">#}
{#                <a class="nav-link js-scroll active" href="#home">خانه</a>#}
{#              </li>#}
{##}
{#              <li class="nav-item">#}
{#                <a class="nav-link js-scroll" href="#about">درباره ما</a>#}
{#              </li>#}
{##}
{#              <li class="nav-item">#}
{#                  <a class="nav-link js-scroll" href="#clinic">مجموعه</a>#}
{#                </li>#}
{##}
{#              <li class="nav-item">#}
{#                  <a class="nav-link js-scroll" href="#contactMe">تماس با ما</a>#}
{#                </li>#}
{##}
{#                <li class="nav-item">#}
{#                    <a class="nav-link js-scroll" href="#service">خدمات</a>#}
{#                  </li>#}
{##}
{#              <li class="nav-item">#}
{#                <a class="nav-link js-scroll" href="#login">ورود</a>#}
{#              </li>#}
{##}
{#              <li class="nav-item">#}
{#                <a class="nav-link js-scroll" href="#register">ثبت نام</a>#}
{#              </li>#}
{#            </ul>#}
{#          </div>#}
{#        </div>#}
{#      </nav>#}


      {% block content %}





      {% endblock content %}








{#      <footer>#}
{#        <div class="container">#}
{#          <div class="row">#}
{#            <div class="col-sm-12">#}
{#              <div class="copyright-box">#}
{#                <p class="copyright">&copy; Copyright 2020 <a href="/" class="text-light"><strong>Wellnes</strong></a>.#}
{#                  All Rights Reserved</p>#}
{#                <div class="credits">#}
{#  #}
{#                  Designed by <a href="#"><strong>Mj</strong></a>#}
{#                </div>#}
{#              </div>#}
{#            </div>#}
{#          </div>#}
{#        </div>#}
{#      </footer>#}




       <!-- JavaScript mylibraries -->
  <script src={% static 'mylib/jquery/jquery.min.js' %}></script>
  <script src={% static 'mylib/jquery/jquery-migrate.min.js' %}></script>
  <script src={% static 'mylib/popper/popper.min.js' %}></script>
  <script src={% static 'mylib/bootstrap/js/bootstrap.min.js' %}></script>
  <script src={% static 'mylib/easing/easing.min.js' %}></script>
  <script src={% static 'mylib/counterup/jquery.waypoints.min.js' %}></script>
  <script src={% static 'mylib/counterup/jquery.counterup.js' %}></script>
  <script src={% static 'mylib/owlcarousel/owl.carousel.min.js' %}></script>
  <script src={% static 'mylib/lightbox/js/lightbox.min.js' %}></script>
  <script src={% static 'mylib/typed/typed.min.js' %}></script>


  <!-- Template Main Javascript File -->
  <script src={% static 'js/main.js' %}></script>
</body>
</html>

TehranMap/templates/base2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>


    <!-- Favicons -->
  <link rel="shortcut icon" type="image/png" href={% static 'photo/favicon.png' %} />

  <!-- Bootstrap CSS File -->
  <link href={% static 'mylib/bootstrap/css/bootstrap.min.css' %} rel="stylesheet">

  <!-- mylibraries CSS Files -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
  <link href={% static 'mylib/font-awesome/css/font-awesome.min.css' %} rel="stylesheet">
  <link href={% static 'mylib/animate/animate.min.css' %} rel="stylesheet">
  <link href={% static 'mylib/ionicons/css/ionicons.min.css' %} rel="stylesheet">
  <link href={% static 'mylib/owlcarousel/assets/owl.carousel.min.css' %} rel="stylesheet">
  <link href={% static 'mylib/lightbox/css/lightbox.min.css' %} rel="stylesheet">
  <link href="{% static 'css/menu.css' %}" rel="stylesheet">

  <!-- Main Stylesheet File -->
  <link href={% static 'css/base.css' %} rel="stylesheet">

    <!---------------------------------------------->
    <style type="text/css">
    @font-face {
      font-family: vazir-thin;
      src: url({% static "font/vazir-font-v19.1.0/Farsi-Digits/Vazir-Thin-FD.woff" %});
    }
    @font-face {
      font-family: vazir-medium;
      src: url({% static "font/vazir-font-v19.1.0/Farsi-Digits/Vazir-Medium-FD.woff" %});
    }
    @font-face {
      font-family: vazir-bold;
      src: url({% static "font/vazir-font-v19.1.0/Farsi-Digits/Vazir-Bold-FD.woff" %});
    }
    @font-face {
      font-family: Vazir Code;
      src: url('{% static "font/vazir-code-font-v1.1.1/Vazir-Code.eot" %}');
      src: url('{% static "font/vazir-code-font-v1.1.1/Vazir-Code.eot" %}'),
           url('{% static "font/vazir-code-font-v1.1.1/Vazir-Code.woff" %}') format('woff'),
           url('{% static "font/vazir-code-font-v1.1.1/Vazir-Code.ttf" %}') format('truetype');
      font-weight: normal;
    }

    @font-face {
      font-family: Vazir Code Hack;
      src: url('{% static "font/vazir-code-font-v1.1.1/Vazir-Code-Hack.eot" %}');
      src: url('{% static "font/vazir-code-font-v1.1.1/Vazir-Code-Hack.eot" %}'),
           url('{% static "font/vazir-code-font-v1.1.1/Vazir-Code-Hack.woff" %}') format('woff'),
           url('{% static "font/vazir-code-font-v1.1.1/Vazir-Code-Hack.ttf" %}') format('truetype');
      font-weight: normal;
    }
  </style>
</head>
<body id="page-top">
    <nav class="navbar navbar-b navbar-trans navbar-expand-md fixed-top" id="mainNav">
        <div class="container">
          <a class="navbar-brand js-scroll" href="#page-top">Wellnes</a>
          <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarDefault"
            aria-controls="navbarDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span></span>
            <span></span>
            <span></span>
          </button>
          <div class="navbar-collapse collapse justify-content-end" id="navbarDefault">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link js-scroll active" href="#home">خانه</a>
              </li>

              <li class="nav-item">
                <a class="nav-link js-scroll" href="#about">درباره ما</a>
              </li>

              <li class="nav-item">
                  <a class="nav-link js-scroll" href="#clinic">مجموعه</a>
                </li>

              <li class="nav-item">
                  <a class="nav-link js-scroll" href="#contactMe">تماس با ما</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link js-scroll" href="#service">خدمات</a>
                  </li>

              <li class="nav-item">
                <a class="nav-link js-scroll" href="#login">ورود</a>
              </li>

              <li class="nav-item">
                <a class="nav-link js-scroll" href="#register">ثبت نام</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>


      {% block content %}





      {% endblock content %}








{#      <footer>#}
{#        <div class="container">#}
{#          <div class="row">#}
{#            <div class="col-sm-12">#}
{#              <div class="copyright-box">#}
{#                <p class="copyright">&copy; Copyright 2020 <a href="/" class="text-light"><strong>Wellnes</strong></a>.#}
{#                  All Rights Reserved</p>#}
{#                <div class="credits">#}
{#  #}
{#                  Designed by <a href="#"><strong>Mj</strong></a>#}
{#                </div>#}
{#              </div>#}
{#            </div>#}
{#          </div>#}
{#        </div>#}
{#      </footer>#}




       <!-- JavaScript mylibraries -->
  <script src={% static 'mylib/jquery/jquery.min.js' %}></script>
  <script src={% static 'mylib/jquery/jquery-migrate.min.js' %}></script>
  <script src={% static 'mylib/popper/popper.min.js' %}></script>
  <script src={% static 'mylib/bootstrap/js/bootstrap.min.js' %}></script>
  <script src={% static 'mylib/easing/easing.min.js' %}></script>
  <script src={% static 'mylib/counterup/jquery.waypoints.min.js' %}></script>
  <script src={% static 'mylib/counterup/jquery.counterup.js' %}></script>
  <script src={% static 'mylib/owlcarousel/owl.carousel.min.js' %}></script>
  <script src={% static 'mylib/lightbox/js/lightbox.min.js' %}></script>
  <script src={% static 'mylib/typed/typed.min.js' %}></script>


  <!-- Template Main Javascript File -->
  <script src={% static 'js/main.js' %}></script>
</body>
</html>

TehranMap/templates/list.html
{% extends "base2.html" %}

{% block content %}

 <!--/ Intro Skew Star /-->
 <div id="home" class="intro route bg-image" style="/*background-image: url(/static/img/back-top.jpg)*/">
    <div class="overlay-itro" >
    <div class="intro-content display-table">
      <div class="table-cell">
        <div class="container">

            <div class="row center m-auto title-menu" >
                <strong class="m-auto " style="font-size: 48px;color: purple; opacity: 100%">مراکز {{ clubs.first.group }} منطقه : {{ clubs.first.region }} {{ region }}</strong>
            </div>
            {% if clubs %}

                    <div class="row" style="margin-top: 100px" >
                    {% for club in clubs %}

                    <div class="col-md-12 col-8 card-row" >
                        <div class="card  text-white text-center p-3 card-compelex-list">
                            <blockquote class="blockquote mb-0">
                              <a class="p-card-menu" href="{{ region }}/1">{{ club.name }}</a>
    {#                          <footer class="blockquote-footer text-white">#}
    {#                            <small>#}
    {#                              Someone famous in <cite title="Source Title">Source Title</cite>#}
    {#                            </small>#}
    {#                          </footer>#}
                            </blockquote>
                        </div>
                    </div>
                    <br>
                    <br>
                    <br>
                    <br>
                    {% endfor %}

                    </div>


            {% endif %}


        </div>
      </div>
    </div>
    </div>
  </div>
  <!--/ Intro Skew End /-->

{% endblock content %}

TehranMap/templates/menu.html
{% extends "base2.html" %}

{% block content %}

 <!--/ Intro Skew Star /-->
 <div id="home" class="intro route bg-image" style="/*background-image: url(/static/img/back-top.jpg)*/">
    <div class="overlay-itro" >
    <div class="intro-content display-table">
      <div class="table-cell">
        <div class="container">

            <div class="row center m-auto title-menu" >
                <strong class="m-auto " style="font-size: 48px;color: purple; opacity: 100%">مراکز منطقه : {{ region }}</strong>
            </div>
            <div class="row" style="margin-top: 100px" >
                <div class="col-md-5 col-8 card-row" >
                    <div class="card  text-white text-center p-3 card-compelex">
                        <blockquote class="blockquote mb-0">
                          <a class="p-card-menu" href="{{ region }}/1">باشگاه های فیتنس</a>
{#                          <footer class="blockquote-footer text-white">#}
{#                            <small>#}
{#                              Someone famous in <cite title="Source Title">Source Title</cite>#}
{#                            </small>#}
{#                          </footer>#}
                        </blockquote>
                    </div>
                </div>

            </div>
            <br>
            <div class="row" >
                <div class="col-md-5 col-8 card-row" >
                    <div class="card  text-white text-center p-3 card-compelex">
                        <blockquote class="blockquote mb-0">
                          <a class="p-card-menu" href="{{ region }}/2">مراکز ماساژ</a>
{#                          <footer class="blockquote-footer text-white">#}
{#                            <small>#}
{#                              Someone famous in <cite title="Source Title">Source Title</cite>#}
{#                            </small>#}
{#                          </footer>#}
                        </blockquote>
                    </div>
                </div>

            </div>
            <br>
            <div class="row" >
                <div class="col-md-5 col-8 card-row" >
                    <div class="card  text-white text-center p-3 card-compelex">
                        <blockquote class="blockquote mb-0">
                          <a class="p-card-menu" href="{{ region }}/3">مراکز خدماتی و آرایشی</a>
{#                          <footer class="blockquote-footer text-white">#}
{#                            <small>#}
{#                              Someone famous in <cite title="Source Title">Source Title</cite>#}
{#                            </small>#}
{#                          </footer>#}
                        </blockquote>
                    </div>
                </div>

            </div>

        </div>
      </div>
    </div>
    </div>
  </div>
  <!--/ Intro Skew End /-->

{% endblock content %}

Wellness/templates/index.html
{% extends "base2.html" %}

{% block content %}

 <!--/ Intro Skew Star /-->
 <div id="home" class="intro route bg-image" style="/*background-image: url(/static/img/back-top.jpg)*/">
    <div class="overlay-itro" >
    <div class="intro-content display-table">
      <div class="table-cell">
        <div class="container">
          <!--<p class="display-6 color-d">Hello, world!</p>-->
          <div class="row title-wellnes"><h1 class="intro-title mb-4" style="margin: auto">Tehran</h1></div>
          <div class="row title-wellnes"><h1 class="intro-title mb-4" style="margin: auto">Wellness</h1></div>
          <p class="intro-subtitle center"  ><span class="text-slider-items">سلامتی شما هدف ماست</span><strong class="text-slider"></strong></p>
          <!-- <p class="pt-3"><a class="btn btn-primary btn js-scroll px-4" href="#about" role="button">Learn More</a></p> -->
{#          <button type="button" class="btn btn-secondary btn-lg btn-block">ورود به نقشه</button>#}

          <div class="row row-button-sm center" >
            <a href="{% url 'login' %}" class="btn btn-default btn-circle btn-xl login-button" style="padding: 0; display: block">
                <button type="button" class="btn btn-default btn-circle btn-xl login-button" style="width: 100%;margin-top: 0!important;" >
                    <span>ورود به حساب</span>
                </button>
            </a>

           <a href="{% url 'tehranMap:map' %}" class="btn btn-default btn-circle btn-xl map-button" style="padding: 0;">
                <button type="button" class="btn btn-default btn-circle btn-xl map-button" style="width: 100%;margin-top: 0!important;">
                    <span>نقشه</span>
                </button>
           </a>
          </div>
        <div class="clearfix">

        </div>
        </div>
      </div>
    </div>
    </div>
  </div>
  <!--/ Intro Skew End /-->

{% endblock content %}